"""Write the Streamlit client's secrets.toml from the deployed stack.

Reads the API URL from the CloudFormation outputs and the bearer token from Secrets
Manager, and writes `client/.streamlit/secrets.toml`. The point is that the token never
passes through a clipboard, a chat window or a shell history on its way to the file.

    python scripts/configure_client.py                       # defaults to kbagent-dev
    python scripts/configure_client.py --stack kbagent-mc-dev
    python scripts/configure_client.py --profile amcro       # the other account

Uses the AWS CLI rather than boto3 so the client folder needs no AWS SDK at all.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "client" / ".streamlit" / "secrets.toml"

# The AWS CLI installs here on Windows and is frequently missing from a shell that was
# opened before it was installed, which is a confusing failure to debug from an error that
# just says "aws: not found".
WINDOWS_CLI = Path(r"C:\Program Files\Amazon\AWSCLIV2\aws.exe")


def aws_binary() -> str:
    found = shutil.which("aws")
    if found:
        return found
    if WINDOWS_CLI.exists():
        return str(WINDOWS_CLI)
    sys.exit(
        "AWS CLI not found. Install it, or open a new terminal if you installed it in this one "
        "(a shell keeps the PATH it was started with)."
    )


def run(args: list[str], profile: str | None) -> str:
    command = [aws_binary(), *args]
    if profile:
        command += ["--profile", profile]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"Command failed: {' '.join(args[:3])}\n{result.stderr.strip()}")
    return result.stdout.strip()


def stack_outputs(stack: str, profile: str | None) -> dict[str, str]:
    raw = run(
        ["cloudformation", "describe-stacks", "--stack-name", stack,
         "--query", "Stacks[0].Outputs", "--output", "json"],
        profile,
    )
    return {o["OutputKey"]: o["OutputValue"] for o in json.loads(raw or "[]")}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--stack", default="kbagent-dev", help="CloudFormation stack name")
    parser.add_argument("--profile", default=None, help="AWS CLI profile")
    args = parser.parse_args()

    outputs = stack_outputs(args.stack, args.profile)
    api_url = outputs.get("ApiBaseUrl")
    secret_name = outputs.get("ApiTokenSecret") or f"{args.stack}/api-token"
    if not api_url:
        sys.exit(f"Stack {args.stack!r} has no ApiBaseUrl output. Has it been deployed?")

    token = run(
        ["secretsmanager", "get-secret-value", "--secret-id", secret_name,
         "--query", "SecretString", "--output", "text"],
        args.profile,
    )

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        "# Generated by scripts/configure_client.py -- do not commit.\n"
        f'API_BASE_URL = "{api_url}"\n'
        f'API_TOKEN    = "{token}"\n',
        encoding="utf-8",
    )

    # Length rather than value: enough to confirm it worked, not enough to leak.
    print(f"Wrote {TARGET.relative_to(ROOT)}")
    print(f"  API_BASE_URL = {api_url}")
    print(f"  API_TOKEN    = {len(token)} characters (not shown)")
    print("\nNow run:  streamlit run client/streamlit_app.py")

    # Cheap insurance against the one mistake that actually matters here.
    gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
    if "secrets.toml" not in gitignore:
        print("\nWARNING: .gitignore does not exclude secrets.toml. Fix that before committing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
